plugins {
  id 'application'
}

ext {
  moduleName = 'Rectify Sqlline'
  moduleDescription = 'Rectify support for Sqlline'
}

application {
  mainClass = 'sqlline.SqlLine'
}

dependencies {
  implementation project(":febit-rectify-core")
  implementation 'org.apache.calcite:calcite-core'
  implementation 'sqlline:sqlline'
}
